# Generated by Django 4.1.5 on 2023-01-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='car_type',
            field=models.CharField(choices=[('suv', 'SUV'), ('hatchback', 'Hatchback'), ('crossover', 'Crossover'), ('convertible', 'Convertible'), ('sedan', 'Sedan'), ('sports', 'Sports'), ('coupe', 'Coupe'), ('minivan', 'Minivan'), ('station wagon', 'Station Wagon'), ('pickup truck', 'Pickup Truck')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addproduct',
            name='owner_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
