# Generated by Django 4.1.5 on 2023-01-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_addproduct_car_type_addproduct_owner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addproduct',
            options={'verbose_name': 'Product Details', 'verbose_name_plural': 'Add Product'},
        ),
        migrations.RenameField(
            model_name='addproduct',
            old_name='user',
            new_name='email',
        ),
    ]
