# Generated by Django 4.1.5 on 2023-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_addproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
