# Generated by Django 4.1.5 on 2023-01-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_addproduct_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
