# Generated by Django 4.1.5 on 2023-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_addproduct_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='car_number',
            field=models.CharField(default=111, max_length=15),
            preserve_default=False,
        ),
    ]
