# Generated by Django 4.1.5 on 2023-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_addproduct_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='car_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
