# Generated by Django 4.1.5 on 2023-01-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0005_alter_addproduct_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoookedCarDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_type', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=150)),
                ('date_of_pickup', models.DateField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='owner.addproduct')),
            ],
            options={
                'verbose_name': 'Booked Car ',
                'verbose_name_plural': 'Booked Car',
            },
        ),
    ]
