# Generated by Django 4.1.5 on 2023-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boookedcardetail',
            name='car_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
